services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./Backend/.env
    expose:
      - "3000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: arete-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
